<x-app-layout>
    @section('breadcrumb')
        <x-breadcrumb :items="[['label' => 'Payroll', 'href' => route('payroll.index')], ['label' => $payroll->employee->full_name . ' — ' . $payroll->period_label]]" />
    @endsection

    <x-slot name="header">
        <div class="flex items-center gap-3">
            <a href="{{ route('payroll.index', ['year' => $payroll->period_year, 'month' => $payroll->period_month]) }}"
               class="text-gray-400 hover:text-gray-600">Payroll</a>
            <span class="text-gray-300">/</span>
            <h2 class="text-xl font-semibold text-gray-800">
                {{ $payroll->employee->full_name }} — {{ $payroll->period_label }}
            </h2>
        </div>
    </x-slot>

    @php
        $statusBadge = match($payroll->status) {
            'draft'     => 'bg-yellow-100 text-yellow-800',
            'finalized' => 'bg-blue-100 text-blue-800',
            'paid'      => 'bg-green-100 text-green-800',
        };
    @endphp

    <div class="max-w-3xl space-y-6">

        <div class="rounded-lg bg-white p-6 shadow">
            <div class="mb-4 flex items-center justify-between">
                <span class="rounded-full px-3 py-1 text-sm font-medium {{ $statusBadge }}">
                    {{ ucfirst($payroll->status) }}
                </span>
                <a href="{{ route('payroll.pdf', $payroll) }}"
                   class="text-sm text-indigo-600 hover:text-indigo-900">Download PDF</a>
            </div>

            <dl class="grid grid-cols-2 gap-4 sm:grid-cols-3">
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Employee</dt>
                    <dd class="mt-1 text-sm font-medium text-gray-900">{{ $payroll->employee->full_name }}</dd>
                </div>
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Department</dt>
                    <dd class="mt-1 text-sm text-gray-700">{{ $payroll->employee->department?->name ?? '—' }}</dd>
                </div>
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Period</dt>
                    <dd class="mt-1 text-sm text-gray-700">{{ $payroll->period_label }}</dd>
                </div>
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Base Salary</dt>
                    <dd class="mt-1 text-sm font-medium text-gray-900">{{ number_format((float)$payroll->base_salary, 2) }}</dd>
                </div>
                <div>
                    <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Generated By</dt>
                    <dd class="mt-1 text-sm text-gray-700">{{ $payroll->generatedBy?->name ?? '—' }}</dd>
                </div>
                @if($payroll->finalized_at)
                    <div>
                        <dt class="text-xs font-medium uppercase tracking-wide text-gray-500">Finalized</dt>
                        <dd class="mt-1 text-sm text-gray-700">{{ $payroll->finalized_at->format('d M Y, H:i') }}</dd>
                    </div>
                @endif
            </dl>
        </div>

        <div class="rounded-lg bg-white p-6 shadow">
            <h3 class="mb-4 text-sm font-semibold text-gray-700">Attendance Summary</h3>
            <div class="grid grid-cols-3 gap-4 text-center">
                <div class="rounded-md bg-green-50 p-3">
                    <p class="text-2xl font-bold text-green-800">{{ $payroll->worked_days }}</p>
                    <p class="text-xs font-medium uppercase tracking-wide text-green-600">Worked Days</p>
                </div>
                <div class="rounded-md bg-red-50 p-3">
                    <p class="text-2xl font-bold text-red-800">{{ $payroll->absent_days }}</p>
                    <p class="text-xs font-medium uppercase tracking-wide text-red-600">Absent Days</p>
                </div>
                <div class="rounded-md bg-orange-50 p-3">
                    <p class="text-2xl font-bold text-orange-800">{{ $payroll->unpaid_leave_days }}</p>
                    <p class="text-xs font-medium uppercase tracking-wide text-orange-600">Unpaid Leave</p>
                </div>
            </div>
        </div>

        <div class="rounded-lg bg-white p-6 shadow">
            <h3 class="mb-4 text-sm font-semibold text-gray-700">Earnings &amp; Deductions</h3>

            <div class="overflow-x-auto">
            <table class="min-w-full text-sm">
                <thead class="text-xs font-medium uppercase tracking-wide text-gray-500">
                    <tr>
                        <th class="py-2 text-left">Description</th>
                        <th class="py-2 text-left">Type</th>
                        <th class="py-2 text-right">Amount</th>
                        @can('removeItem', $payroll)
                            <th class="py-2"></th>
                        @endcan
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    <tr>
                        <td class="py-2 text-gray-700">Base Salary</td>
                        <td class="py-2"><span class="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-800">Earning</span></td>
                        <td class="py-2 text-right font-medium text-green-700">{{ number_format((float)$payroll->base_salary, 2) }}</td>
                        @can('removeItem', $payroll)<td></td>@endcan
                    </tr>
                    @foreach($payroll->items as $item)
                        <tr>
                            <td class="py-2 text-gray-700">{{ $item->label }}</td>
                            <td class="py-2">
                                @if($item->type === 'bonus')
                                    <span class="rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-800">Bonus</span>
                                @else
                                    <span class="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-800">Deduction</span>
                                @endif
                            </td>
                            <td class="py-2 text-right font-medium {{ $item->type === 'bonus' ? 'text-green-700' : 'text-red-700' }}">
                                {{ $item->type === 'bonus' ? '+' : '-' }}{{ number_format((float)$item->amount, 2) }}
                            </td>
                            @can('removeItem', $payroll)
                                <td class="py-2 text-right">
                                    <span x-data>
                                        <form method="POST" action="{{ route('payroll.items.destroy', [$payroll, $item]) }}" x-ref="deleteForm" class="hidden">
                                            @csrf @method('DELETE')
                                        </form>
                                        <button type="button" class="text-xs text-red-500 hover:text-red-700"
                                                @click="$dispatch('confirm', { title: 'Remove Item', message: 'This bonus/deduction will be removed and the net salary recalculated.', onConfirm: () => $refs.deleteForm.submit() })">
                                            Remove
                                        </button>
                                    </span>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
                <tfoot class="border-t-2 border-gray-300">
                    <tr>
                        <td class="pt-3 font-bold text-gray-900" colspan="2">Net Salary</td>
                        <td class="pt-3 text-right text-lg font-bold text-gray-900">{{ $payroll->net_salary_formatted }}</td>
                        @can('removeItem', $payroll)<td></td>@endcan
                    </tr>
                </tfoot>
            </table>
            </div>
        </div>

        @can('addItem', $payroll)
            <div class="rounded-lg bg-white p-6 shadow">
                <h3 class="mb-4 text-sm font-semibold text-gray-700">Add Bonus / Deduction</h3>
                <form method="POST" action="{{ route('payroll.items.store', $payroll) }}"
                      class="grid grid-cols-1 gap-3 sm:grid-cols-4">
                    @csrf
                    <div>
                        <x-input-label for="item_type" value="Type" />
                        <select id="item_type" name="type"
                                class="mt-1 block w-full rounded-md border-gray-300 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                            <option value="bonus"     @selected(old('type') === 'bonus')>Bonus</option>
                            <option value="deduction" @selected(old('type') === 'deduction')>Deduction</option>
                        </select>
                        <x-input-error :messages="$errors->get('type')" class="mt-1" />
                    </div>
                    <div class="sm:col-span-2">
                        <x-input-label for="item_label" value="Label" />
                        <x-text-input id="item_label" name="label" type="text" class="mt-1 block w-full"
                                      value="{{ old('label') }}" placeholder="e.g. Performance Bonus" required />
                        <x-input-error :messages="$errors->get('label')" class="mt-1" />
                    </div>
                    <div>
                        <x-input-label for="item_amount" value="Amount" />
                        <x-text-input id="item_amount" name="amount" type="number" step="0.01" min="0.01"
                                      class="mt-1 block w-full" value="{{ old('amount') }}" required />
                        <x-input-error :messages="$errors->get('amount')" class="mt-1" />
                    </div>
                    <div class="sm:col-span-4">
                        <x-primary-button>Add Item</x-primary-button>
                    </div>
                </form>
            </div>
        @endcan

        <div class="flex flex-wrap gap-3">
            @can('finalize', $payroll)
                <form method="POST" action="{{ route('payroll.finalize', $payroll) }}"
                      onsubmit="return confirm('Finalize this payroll? This cannot be undone.');">
                    @csrf
                    <button type="submit"
                            class="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700">
                        Finalize Payroll
                    </button>
                </form>
            @endcan

            @can('markPaid', $payroll)
                <form method="POST" action="{{ route('payroll.paid', $payroll) }}"
                      onsubmit="return confirm('Mark this payroll as paid?');">
                    @csrf
                    <button type="submit"
                            class="rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700">
                        Mark as Paid
                    </button>
                </form>
            @endcan
        </div>

    </div>
</x-app-layout>
